### ISSUE TITLE
Compiling on Windows - Visual Studio 2019 - ClangCL

### ISSUE THREAD

**Issue by colinsenner** [SheLLVM/SheLLVM#3]
I'm attempting to compile this on windows using clang-cl.

I ran cmake with the following:

`cmake -G "Visual Studio 16 2019" -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_INSTALL_PREFIX=C:/Program\ Files/SheLLVM -A x64 -T ClangCL ..`

I'm getting and error when compiling the shellvm project:

"no matching function for call to 'Create' - shellvm - MergeCallsPass.h - line 119

`
    CallInst *UnifiedCall = CallInst::Create(
        cast<Value>(Target), ArrayRef<Value *>(CallArgs), "", CallBlock);
`

Any insight what might be causing this?  Thanks.

**Comment by Psychotropos** [comment]
Thank you for reporting this. Support for LLVM >= 10 has been introduced as of c6979469faa949d8c1030027236581361798577e.
